version: '3.3'

services:

  prometheus:
    build:
      context: prometheus
    volumes:
      - prometheus-data:/prometheus
      - type: bind
        source: ./scrape-targets
        target: /prometheus/targets
    restart: always
    network_mode: host

  grafana:
    build:
      context: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always
    network_mode: host

  geth:
    image: ethereum/client-go:stable
    container_name: geth
    restart: unless-stopped
    ports:
      - '8545:8545'
      - '8546:8546'
      - '30303:30303/tcp'
      - '30303:30303/udp'
    volumes:
      - data:/root
    command:
      - --ws
      - --ws.addr=0.0.0.0
      - --http
      - --http.addr=0.0.0.0
#     - --http.corsdomain=[read below]
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*

  lighthouse:
    image: sigp/lighthouse:latest-modern
    container_name: lighthouse
    restart: unless-stopped
    ports:
      - '9000:9000/tcp'
      - '9000:9000/udp'
      - '127.0.0.1:5052:5052'
    volumes:
      - lighthouse:/root/.lighthouse
      - data:/geth/:ro
    command:
      - lighthouse
      - --network=mainnet
      - beacon
      - --metrics
      - --http
      - --http-address=0.0.0.0
      - --execution-endpoint=http://geth:8551
      - --execution-jwt=/geth/.ethereum/geth/jwtsecret
      - --checkpoint-sync-url=https://beaconstate.info/

volumes:
  data:
  lighthouse:
  grafana-data:
  prometheus-data:
  targets: